"""add_phone_number

Revision ID: 05c64f01d67d
Revises: ffd224ec36fa
Create Date: 2022-12-25 10:03:22.015853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c64f01d67d'
down_revision = 'ffd224ec36fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint("ph_uni", 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ph_uni", 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
