"""add_mobile_number

Revision ID: 82cc1f57779a
Revises: 05c64f01d67d
Create Date: 2022-12-25 10:13:46.322147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cc1f57779a'
down_revision = '05c64f01d67d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint("mob_num_uni", 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mob_num_uni", 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
